detectors:
  DuplicateMethodCall:
    enabled: false
  FeatureEnvy:
    enabled: false
  IrresponsibleModule:
    enabled: false
  NestedIterators:
    enabled: false
  NilCheck:
    enabled: false
  TooManyStatements:
    enabled: false
  UtilityFunction:
    enabled: false
  LongParameterList:
    exclude:
      - "RecipeHelper#rating_stars"
      - "ImageReader#call"
      - "PennyLunch::Quality::EnvAccessScanner#scan_file"
  ControlParameter:
    exclude:
      - "RecipeSortQuery#call"
  TooManyConstants:
    exclude:
      - "RecipeSortQuery"
      - "ImageReader"
      - "RecipeImport"
  TooManyMethods:
    exclude:
      - "ImageReader"
  ManualDispatch:
    exclude:
      - "ImageReader#uploaded_image_data_url"

exclude_paths:
  - bin
  - config
  - db
  - lib/tasks
  - spec
  - test
  - tmp
  - vendor
